name: Create Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: fresh-time-kick-${{ github.ref }}.zip
      - name: Curl zip
        shell: bash
        run: |
          curl -H "Authorization: ApiKey ${{ secrets.EDGE_CLIENT_SECRET }}" \
            -H "X-ClientID: ${{ secrets.EDGE_CLIENT_ID }}" \
            -H "Content-Type: application/zip" \
            -X POST \
            -T fresh-time-kick-${{ github.ref }}.zip \
            -v \
            https://api.addons.microsoftedge.microsoft.com/v1/products/${{ secrets.EDGE_PRODUCT_ID }}/submissions/draft/package/package
      - name: Curl publish
        shell: bash
        run: |
          curl -H "Authorization: ApiKey ${{ secrets.EDGE_CLIENT_SECRET }}" \
            -H "X-ClientID: ${{ secrets.EDGE_CLIENT_ID }}" \
            -X POST \
            -d '{ "notes"="Update" }' \
            -v \
            https://api.addons.microsoftedge.microsoft.com/v1/products/${{ secrets.EDGE_PRODUCT_ID }}/submissions
